# Generated by Django 5.0.6 on 2024-06-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="item",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
